# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: XTRABYTES Test Network
email: xtrabytesofficial@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  A progress bar that shows the number of testers required to start
  the XtraBYtes STaTiC Test Network.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xtrabytes.global/" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: xtrabytes
github_username:  borzalom

# Contact lines for required testers
tester_line: "be a tester"
tester_link: "https://bitcointalk.org/index.php?topic=1864397.msg21165887#msg21165887"

# Quantity of required testers
testers_quantity_total: 512

# Link with instructions for new testers
new_testers_link: ""

# Build settings
markdown: kramdown
theme: minima
